cart/urls.py
from django.conf.urls import url
from . import views
from cart.views import OrdersDeatil
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^my_current_orders/$', OrdersDeatil.as_view(), name='my_orders'),
]

fastook/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls','carts'), namespace='cart')),
    url(r'^orders/', include(('orders.urls','carts'), namespace='orders')),
    url(r'^clients/', include(('clients.urls','carts'), namespace='clients')),
    url(r'^', include(('taverns.urls','taverns'), namespace='taverns')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taverns/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.http import HttpResponse
from django.views.generic import TemplateView
from . import views
from taverns.views import *
from clients.views import LoginFormView, LogoutView
from django.conf.urls import *

app_name = 'taverns'


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^login/$',LoginFormView.as_view()),
    url(r'^locations/$',show_nearest_cafes),
    url(r'^logout/$',LogoutView.as_view()),
    url(r'^places/(?P<slug>[-\w]+)/$', views.show_tavern, name='detali'), 
    url(r'^products/(?P<slug>[-\w]+)/$',  views.show_product, name='detail'),
]

taverns/models.py
from django.db import models
from django.urls import reverse
#from clients.models import Client
from geo import convert_adres, insert_cafe_from_fastook, dj_cafe_insert_cafes


# Create your models here.
class Taverna(models.Model):

    owner = models.ForeignKey('clients.Owner', related_name = 'owner', on_delete = models.CASCADE, verbose_name="владелец", default=1)
    icon = models.ImageField(upload_to='place_icons/', blank=True, verbose_name="Аватарка заведения", default = 'place_icons/default.png')
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")

    city = models.CharField(max_length=200, db_index=True, verbose_name="Город", default ="")
    street = models.CharField(max_length=200, db_index=True, verbose_name="Улица", default ="")
    building = models.CharField(max_length=200, db_index=True, verbose_name="Дом", default ="")

    slug = models.SlugField(max_length=200, db_index=True,blank=True)
    work_time = models.CharField(max_length=200, db_index=True, verbose_name="Время работы")

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'name', 'slug']
        ]
        verbose_name = 'Заведение'
        verbose_name_plural = 'Заведения'   



    def  __str__(self): 
        return str(self.name)
        pass


    def get_absolute_url(self):
        return reverse('taverns:detali', args=[str(self.slug)])
        pass

    def full_adress(self):
        return 'Беларусь,{city}, {street},{build}'.format(city = self.city, street = self.street, build = self.building)
        pass
        
    def addres_to_coord(self):
        return convert_adres(self.full_adress())
        pass



    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        cafe_coords = convert_adres(self.full_adress())
        print(cafe_coords)
        insert_com = insert_cafe_from_fastook.format(
                                id = 3363+self.id+2222, 
                                name = "'"+self.name+"'", 
                                adr = "'"+self.full_adress()+"'",
                                lon = cafe_coords['longitude'],
                                lat = cafe_coords['latitude'], 
                                dj_id = self.id,
                                )

        dj_cafe_insert_cafes(insert_com) 

        return True
        pass




class Product(models.Model):

    place = models.ForeignKey(Taverna, related_name='products', on_delete=models.CASCADE, blank=True, verbose_name="Заведение")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара",default = 'products/deafult.png')
    price = models.FloatField(db_index=True, blank=True, verbose_name="Цена")
    weight =  models.CharField(max_length=50, db_index=True, blank=True, verbose_name="Вес")
    description = models.TextField(blank=True, verbose_name="Описание")
   
    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'name', 'slug']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return str(self.name)

        
    def get_absolute_url(self):
        return reverse('taverns:detail', args=[str(self.slug)])

#        http://dikiigrigorii.ru/blog/article/internet-magazin-na-django-stranica-zakazov-chast-6/19/

taverns/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from taverns.models import Taverna, Product
from django.views.generic.detail import DetailView
from clients.models import Owner as Client

from cart.forms import CartAddProductForm

import geo

def main(request):
	places = Taverna.objects.all()
	return render(request, 'places/taverns_list.html', {'places':places})
	pass


def show_tavern(request, slug):
	place = get_object_or_404(Taverna, slug=slug)
	products = Product.objects.filter(place=place)
	return render(request, 'places/taverna.html',{'place':place, 'products': products})
	pass



def show_product(request, slug):
	product = get_object_or_404(Product, slug=slug)
	cart_product_form = CartAddProductForm()
	return render(request, 'places/eda.html',{'product': product,'cart_product_form':cart_product_form})
	pass




def show_nearest_cafes(request):

	if request.method == 'POST':
		client_loc = request.POST['coords'].split(',')
		search_radius = float(request.POST['search_radius'])

		#accuracy = float(client_loc[2])
		lat = float(client_loc[0])
		lon = float(client_loc[1])
		places = geo.create_locations_table({'lat':lat, 'lon':lon},search_radius)  

		if request.POST['custom_adress']:
			if len(request.POST['custom_adress']) > 5:
				coords = geo.convert_adres('г.Минск,{}'.format(request.POST['custom_adress'])) 

				places = geo.create_locations_table({'lat': coords['latitude'], 'lon':coords['longitude']},search_radius)  
				lat = coords['latitude']
				lon = coords['longitude']        


		list_of_addr = []

		
		for place in places:
			if place[6] != None:
				list_of_addr += [
							{
							'name': place[0],
							'adres': place[4], 
							'coords':[place[2], place[3]], 
							'way_long': geo.haversine(lat,lon, place[3], place[2]),
							'marker':Taverna.objects.get(id=place[6]).get_absolute_url(),}]
			else:
				list_of_addr += [
							{
							'name': place[0],
							'adres': place[4], 
							'coords':[place[2], place[3]], 
							'way_long': geo.haversine(lat,lon, place[3], place[2]),
							'marker':'empty',
							}]




		list_of_addr = sorted(list_of_addr, key=lambda k: k['way_long']) 

		return render(request, 'places/nearest_places.html',  {'places':list_of_addr})
		pass
	else:
		return render(request, 'places/nearest_places.html', {'places':[]})
		pass




'''
https://postgis.net/docs/ST_MakePoint.html
ST_MakePoint(-71.1043443253471, 42.3150676015829);
add new_place into cafes  - name, coors, point, etc.
add field - lon, lat (from point to X or Y)




'''



#pg-U locator
#pg_dump -U locator gis_test > gis_test_work
"""
create user locator with password 'password';
create database obj_data owner locator;

grant all privileges on database obj_data to locator;


create database obj_data owner locator;



pg_dump -U locator gis_test > gis_test_work
psql dj_fast < fastook_work_base

create user egor_f with password 'password';
create database dj_fast owner egor_f;

        'NAME': 'dj_fast',
        'USER': 'egor_f',


        'NAME': 'dj_fast',
        'USER': 'egor_f',
        'PASSWORD': 'password',



ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO locator;
GRANT USAGE ON SCHEMA public to locator;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO locator;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO locator;
ALTER ROLE locator WITH Superuser;

CREATE TABLE obj_locations( obj_name VARCHAR, obj_type VARCHAR, obj_lon numeric, obj_lat numeric, obj_osm_id bigint);
"""

taverns/templates/places/eda.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
|{{product.name}}
{% endblock %}
{% block content %}
<!--жранинка-->
<!--ОПИСАНИЕ С ФОТО -->
<!-- ЗАКАЗ -->
<div class="row justify-content-center">


<div class="card w-50 border success" >
  <div class="card-header">
<h3 class="card-title">{{product.name}}</h3>
</div>
    <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" alt="Card image cap">  <div class="card-body">
    
    <p class="card-text">{{product.description}}</p>
  </div>

  <form action="{% url "cart:CartAdd" product.id %}" method="post" class="ml-3 mb-3">
     {{ cart_product_form.quantity }}
    {% csrf_token %}
    <input type="submit"  class="btn btn-primary" value="Добавить в корзину">
</form>
</div>

</div>
<!--Вес:цена(выбор)
ФОРМА ЗАКАЗА: кнопка "заказать"-->

{% endblock %}



taverns/templates/places/nearest_places.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
| Ближайшие заведения
{% endblock %}
{% block content %}

<div class="row">
<div ckass = "col-12">
  <div class="col-md-3 col-sm-4 col-xs-6 color-1">
    <form method="post" action="" >
      <div class="form-group">
        <input type="text" name="coords" id="client_coords" value="" >
          Введите свой адрес:<input type="text" name="custom_adress" id="client_adress" value="">

        <select name="search_radius">
          <option value="0.001" selected>100 м.</option>
           <option value="0.003">300 м.</option>
           <option value="0.01">1 км.</option>
           <option value="0.03">3 км.</option>
           <option value="0.05">5 км</option>
        </select>      


        <input type="submit" value="Найти ближайшие кафе" class="btn btn-primary">
          {% csrf_token %}
      </div>
    </form>
  </div>
</div>



{%for place in places%}


{% if place.marker == 'empty' %}
<div class="col-md-4 mb-4">
  <div class="card border success border border-secondary">
    <div class="card-body">
      <h4 class="card-title">
        <p class="text-secondary">{{place.name}}</p>
      </h4>
      <p class="card-text" style="height: 50px;">По адресу: {{place.adres}}</p>
      <p class="card-text">В {{place.way_long}} км. от вас.</p>
    </div>

  </div>
</div>

{%else%}


<div class="col-md-4 mb-4">
  <div class="card border success border border-primary">
    <div class="card-body">
      <h4 class="card-title">
         <a href="{{place.get_absolute_url}}" class="font-weight-bold">{{place.name}}</a>
      </h4>
      <p class="card-text" >По адресу: {{place.adres}}</p>
      <p class="card-text">В {{place.way_long}} км. от вас.</p>  
      <p class="card-text">
        <a href="{{place.marker}}" class="card-title"> ОТКРЫТЬ ПРОФИЛЬ ЗАВЕДЕНИЯ</a>
      </p>
    </div>
  </div>
</div>
{%endif%}

{%endfor%}



 </div> 

<div id="mapid" style="width: 850px; height: 600px; margin: 50px"></div>
<script>
window.onload = function() {
  if (navigator.geolocation) {

    navigator.geolocation.getCurrentPosition(
      geolocationSuccess, geolocationFailure, 
        
        {
        enableHighAccuracy: true,
        timeout: 10000,
        maximumAge: 60000
          }
    );

    console.log("Поиск начался");
  }

  else {alert("Ваш браузер не поддерживает геолокацию")}
};

function geolocationSuccess(position) {
  var my_position = [position.coords.latitude, position.coords.longitude]
  var list_of_adreses = {{places|safe}}
  

  var mymap = L.map('mapid').setView(my_position,15);



  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
      '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
      'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    id: 'mapbox.streets'
  }).addTo(mymap);

  L.marker(my_position).addTo(mymap).bindPopup('ВЫ ЗДЕСЬ').openPopup();



  document.getElementById('client_coords').value =[
              position.coords.latitude,
              position.coords.longitude,
              position.coords.accuracy
              ];

  for (var x =0; x < list_of_adreses.length; x++) {

    L.marker(
        [list_of_adreses[x]['coords'][1], 
         list_of_adreses[x]['coords'][0]]
         ).addTo(mymap)
          .bindPopup(
                '<b>'+list_of_adreses[x]['name']+'</b>'
                 +'<br>'+list_of_adreses[x]['adres']
                 +'<br>'+'в '+list_of_adreses[x]['way_long']+' км. от вас'
                );
    };

};


function geolocationFailure(positionError) {
  if(positionError) {
    alert("Вы решили не предоставлять данные о своем местоположении, " + 
            "но это не проблема. Мы больше не будем запрашивать их у вас."+"Но реузльтат выйдет довольно не точный");

    document.getElementById('client_coords').value = 'no coords';
  }

};



</script>


{% endblock %}


taverns/templates/places/taverna.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
|{{place}}
{% endblock %}
{% block content %}
<!--список жранины-->

<div class="row">
{%for product in products%}
<div class="col-md-4">

  <div class="card border success">
    <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" alt="Card image cap" style="height: 250px;">
    <div class="card-body">
      <h4 class="card-title"><a href="{{product.get_absolute_url}}" class="font-weight-bold">{{product.slug}}</a></h4>
      <p class="card-text">{{product.description}}</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">цена: {{product.price}}</small>
      <small class="text-muted">вес:{{product.weight}}</small>
    </div>
  </div>
  </div>
{% endfor %}
</div>



<div id="mapid" style="width: 850px; height: 600px; margin: 50px"></div>
<script>

  var place_coords = {{place.addres_to_coord|safe}}
  var place_position = [place_coords['latitude'], place_coords['longitude']]
  var place_name = {{place.name|safe}}


  var mymap = L.map('mapid').setView(place_position,15);



  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
      '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
      'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    id: 'mapbox.streets'
  }).addTo(mymap);

  L.marker(place_position).addTo(mymap).bindPopup('ss').openPopup();


</script>




{% endblock %}


taverns/templates/places/taverns_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
| Таверны
{% endblock %}
{% block content %}


<div class="row">

{%for place in places%}
<div class="col-md-4">

  <div class="card border success">
    <img class="card-img-top" src="{% if place.icon %}{{ place.icon.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" alt="Card image cap" style="height: 280px;">
    <div class="card-body">
      <h4 class="card-title"><a href="{{place.get_absolute_url}}" class="font-weight-bold">{{place.name}}</a></h4>
      <p class="card-text">Шаурменная по аддресу такому-то готовит для вас жранину, собака дурная</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Адрес:{{place.adres}}</small>
      <small class="text-muted">Адрес:{{place.coords}}</small>
      <br>
      <small class="text-muted">Время работы:{{place.work_time}}</small>
      {{place.id}}
    </div>
  </div>
  </div>

{%endfor%}

 </div> 
{% endblock %}
